### ISSUE TITLE
Future thought: Add visual aids to ARI plots

### ISSUE THREAD

**Issue by allyhawkins** [AlexsLemonade/scpca-downstream-analyses#109]
@allyhawkins I generally agree. Something one _could_ do is add a gray shaded region between 0.5-0.6 on the y-axis, but this is an unreasonable amount of visual noise. 

This is probably something to keep in back pocket to add in later if it becomes clear that ARI interpretation is causing confusion.

_Originally posted by @sjspielman in https://github.com/AlexsLemonade/scpca-downstream-analyses/issues/106#issuecomment-1127820871_

This is in reference to the ARI plots where we show an ARI from each iteration of bootstrapping, we could add visual aids to help users interpret a good vs. bad ARI but want to be careful of not adding too much noise, but we also probably don't want a strict cutoff of "good" and "bad" ARI. This is something we may want to add in the future.

**Comment by cbethell** [comment]
Going to close this issue now, if we would like to revisit this we can re-open!
