### ISSUE TITLE
Move mapping gene identifiers from separate script to function run within GOI calculations script

### ISSUE THREAD

**Issue by allyhawkins** [AlexsLemonade/scpca-downstream-analyses#172]
**Please provide some background on the proposed additions or changes.**

Currently in the GOI module we have a separate script that is used for mapping gene identifiers and is an optional step that is run in the bash script. Since we are moving to have this module as a Snakefile that renders the GOI report, and snakemake doesn't like optional steps, we should take what is currently the [`map-goi-list.R` script](https://github.com/AlexsLemonade/scpca-downstream-analyses/blob/main/utils/map-goi-list.R) and turn it into a function that is optionally run inside the [`goi-report-template.Rmd`](https://github.com/AlexsLemonade/scpca-downstream-analyses/blob/main/optional-goi-analysis/goi-report-template.Rmd) upon rendering. 

**What are the changes that you are proposing?**
 

After moving the current mapping script to be a function, we would source it into the beginning of the template notebook. This would require adjusting the parameters of the template notebook to include an option on whether to include mapping or not as well as input and output identifier types. If that option is specified as true, then mapping would occur prior to plotting for the rest of the notebook. 

**Please describe the proposed solution.**

The current script should be able to be adjusted into a function and I don't believe any of the arguments should have to change. We will just want it to be a function so we can source it in. We will need to add mapping parameters to the template notebook, and I believe that would mean replacing some of the parameters that are currently there for `gene_symbol_column` and `ensembl_id_column`. We probably want to have an `input_gene_list` parameter instead with a `mapping` option and then options for the input gene list type and output gene list type that are only used if mapping is set to true. 

**What potential "gotchas" do we know of?**

Alternatively we could keep things as is and then have two separate steps, one for mapping and one for rendering the notebook in the Snakefile, but I don't think snakemake likes optional outputs so this would be less flexible with optional mapping steps. 

**Additional context or questions**

**Comment by cbethell** [comment]
Just making a note here that we will want to probably move this optional mapping step to a GOI calculations script where we optionally map to gene identifiers and calculate the necessary results for the heatmap for example.

**Comment by allyhawkins** [comment]
Closed by #230
