### ISSUE TITLE
Account for additional `cluster_type` in optional clustering - calculations script

### ISSUE THREAD

**Issue by cbethell** [AlexsLemonade/scpca-downstream-analyses#212]
**Please provide some background on the proposed additions or changes.**

As discussed in a check in meeting, we may want to think about accounting for an additional `cluster_type` in the optional clustering module once we have completed the initial workflow using just one cluster type with multiple nearest neighbors values.
In other words, we will want to allow for `louvain` and `walktrap` clustering with the specified nearest neighbors range of values.

**What are the changes that you are proposing?**

This change will require us to add a feature to the `clustering_calculations.R` script, as well as the template notebook, which will allow the user to specify two `cluster_type`(s), rather than one. 
**Edit:** However this issue should track just updates to the `clustering_calculations.R` script (per the comment left below).

**Please describe the proposed solution.**

Initial thoughts here, we will want to be able to perform two sets of clustering and associated cluster validity/stability calculations on each of the specified cluster types, but still also allow for only one type of clustering if chosen by the user. This will likely mean an if statement of some sort.

**What potential "gotchas" do we know of?**

Not specifically but an if statement handling two versus one clustering type can get a bit tricky.

**Comment by allyhawkins** [comment]
I think I would break this issue up into two separate issues. The first step is modifying the cluster calculations script to take as input one or more clustering types and accounting for that (I think that issue could be added this sprint). I would separate out the second step into its own issue which is modifying the template notebook to deal with multiple clustering types as input.

**Comment by cbethell** [comment]
Addressed by merged PR #224
