### ISSUE TITLE
Refactor GOI template notebook

### ISSUE THREAD

**Issue by cbethell** [AlexsLemonade/scpca-downstream-analyses#231]
**Please provide some background on the proposed additions or changes.**

Once we complete #172, we want to refactor the current GOI template notebook to take the output of the calculations script as input and use that to generate the relevant plots for the report.

**What are the changes that you are proposing?**

The `[optional-goi-analysis/goi-report-template.Rmd](https://github.com/AlexsLemonade/scpca-downstream-analyses/blob/main/optional-goi-analysis/goi-report-template.Rmd)` should be refactored to remove any calculations necessary for plotting, read in the output of the preceding calculations script, and use that to implement the actual plotting steps.

**Please describe the proposed solution.**

More specifically, this involves including the necessary params to read in the output of the calculations script, removing the heatmap preparation steps (they have now been included in PR #230), and generating the plots appropriately.

We may also want to address issue #175 at the same time.

**What potential "gotchas" do we know of?**

None that I can think of at the time, will just want to keep in mind that we will be generating a report for each library id using a snakemake workflow.

**Comment by allyhawkins** [comment]
Closed by #232
