### ISSUE TITLE
Move independent installation instructions to separate doc

### ISSUE THREAD

**Issue by allyhawkins** [AlexsLemonade/scpca-downstream-analyses#235]
**Please provide some background on the proposed additions or changes.**

Right now the presence of two types of installation in the main readme can be confusing, we should move those instructions for the independent installation to avoid confusion. 

**What are the changes that you are proposing?**

Moving everything under the `Independent installation` heading to a new doc.

**Comment by cbethell** [comment]
Addressed by merged PR #248
