### ISSUE TITLE
Include instructions on which mitochondrial gene list to use with data downloaded from scpca-nf

### ISSUE THREAD

**Issue by allyhawkins** [AlexsLemonade/scpca-downstream-analyses#236]
**Please provide some background on the proposed additions or changes.**

In order to run the core workflow users will need to either provide a mitochondrial gene list or use the gene list that we have provided. We briefly mention this in the `project-specific parameters` section, but don't actually expand on how to obtain the list outside of the one we provide. If users are downloading data from `scpca-nf` we have a mitochondrial gene list for them to use, but depending on the version of the index they were aligned to that could dictate which gene list should be used. 

**What are the changes that you are proposing?**

We should include instructions on how to find out which version of the index, and ultimately which reference mito list, should be used for datasets downloaded from `scpca-nf`. 

**Please describe the proposed solution.**

We probably want to include a note in the `project-specific parameters` section on how to find out what mito list to use. This should involve instructions to look at the assembly column of the metadata file associated with that library.

**Comment by cbethell** [comment]
Addressed by merged PR #252
