### ISSUE TITLE
Add section on changes to SCE contents for core workflow 

### ISSUE THREAD

**Issue by allyhawkins** [AlexsLemonade/scpca-downstream-analyses#237]
**Please provide some background on the proposed additions or changes.**

We currently don't describe anywhere what is now included in the `SingleCellExperiment` object that is output from the core workflow. 

**What are the changes that you are proposing?**

We should include a separate section in the expected output that talks about what is actually being added to the SCE object and how to access the changes. This should include things like a new `logcounts` assay, any additions to the `colData` and any additions to the `metadata` list. If this section gets long it may make sense to link out to an additional separate doc instead.

**Comment by cbethell** [comment]
Tackled by merged PR #257
