### ISSUE TITLE
Document the core workflow template

### ISSUE THREAD

**Issue by allyhawkins** [AlexsLemonade/scpca-downstream-analyses#239]
**Please provide some background on the proposed additions or changes.**

The template produced by the core workflow is lacking a lot of documentation and explanation of the plots. The template should be updated to include a description of the expected plots. 

**What are the changes that you are proposing?**

In particular a description of the filtering plot and UMAP is needed. We will need to think about how we want to address describing the filtering plot because different methods of filtering can be used.

**Comment by cbethell** [comment]
Upon addressing this issue, we may also want to get rid of the "0.1, 0.2, etc." pre-fix to each heading, and hide the `Set Up` heading since there is no useful information being displayed under the heading.

**Comment by cbethell** [comment]
Tackled by merged PR #261
