### ISSUE TITLE
Add section on changes to SCE contents for clustering exploration module

### ISSUE THREAD

**Issue by allyhawkins** [AlexsLemonade/scpca-downstream-analyses#240]
**Please provide some background on the proposed additions or changes.**

As noted in #237, we don't have an explanation of what's been modified in the individual SCE objects that are output by the clustering workflow. The contents of the SCE object should be described in the documentation of the clustering module. 

**What are the changes that you are proposing?**

In the clustering module readme section on expected output we should add a subsection on the contents of the SCE. Here we should describe the additions to the `colData` and the `metadata`.

**Comment by cbethell** [comment]
Addressed by #295
