### ISSUE TITLE
Move filtering method from metadata to config file

### ISSUE THREAD

**Issue by allyhawkins** [AlexsLemonade/scpca-downstream-analyses#243]
**Please provide some background on the proposed additions or changes.**

The filtering method is currently required to be listed in the metadata file for each library being processed. This used to be required when we didn't account for failure of `miQC` so each library had to be specified individually in case one failed. However, it doesn't quite make sense now given the addition of all the other params in the config file for it to be in the metadata file and not be in the config file. 

**What are the changes that you are proposing?**

The filtering method should be moved out of the metadata file and into the config file. This will also require changes in the snakemake workflow and how the filtering method is read in. While doing this we should consider changing the workflow from labeling each file with the filtering method since it is included in the report. 

**What potential "gotchas" do we know of?**

This will also require changes to the docs since we currently list the filtering method as being required in the metadata of the workflow.

**Comment by cbethell** [comment]
Addressed by merged PR #255
