### ISSUE TITLE
Generalize GOI plotting functions to include arguments for SCE rownames and IDs to use for plots

### ISSUE THREAD

**Issue by allyhawkins** [AlexsLemonade/scpca-downstream-analyses#253]
**Please provide some background on the proposed additions or changes.**

The plotting functions that are being used in the GOI pipeline currently use arguments that specify a GOI dataframe and then the column names of that GOI dataframe that should be used for plotting. The argument names are `ensembl_id_column` and `gene_symbol_column`. This implies that the rownames of the SCE are always in the ensembl format and plotting will always be with the gene symbol format. Although this may mostly be the case, the naming of these arguments could be more general to follow how we have been naming the rest of the workflow `sce_rownames_column` and `gene_id_column` or `optional_plotting_column`. 

**What are the changes that you are proposing?**

The arguments throughout the plotting functions should be updated to reflect that one of the columns corresponds to the rownames of the SCE objects and the other should correspond to the optional names of genes that should be used for plotting. 
Additionally, we should add in a `use_rownames` option that will tell the function to plot using the rownames for the SCE or to use the optional names column. 

**Please describe the proposed solution.**

The arguments should be renamed from `ensembl_id_column` --> `sce_rownames_column` and `gene_symbol_column` --> `optional_plotting_column` (or something similar). 
The default for the `optional_plotting_column` should be `NULL`.
We should also add a `use_rownames=TRUE` default and add checks that when `use_rownames` is set to `FALSE` a column name has been provided to `optional_plotting_column`. 

**What potential "gotchas" do we know of?**

in addition to the plotting functions, we would also have to update the `prepare_expression_df` function to switch the `ensembl_id_column` to be named `sce_rownames_column`. 

**Additional context or questions**

**Comment by cbethell** [comment]
Addressed by #270
