### ISSUE TITLE
Note minimum snakemake version that is required in the documentation

### ISSUE THREAD

**Issue by jaclyn-taroni** [AlexsLemonade/scpca-downstream-analyses#263]
I performed functional testing of setup and running with the example data on my Ubuntu desktop. A snag I ran into, that I was able to identify as a `snakemake` version issue, is that the argument ` --conda-create-envs-only` didn't exist when I ran the `setup_envs.sh` script. We should:

* Identify what version of snakemake `--conda-create-envs-only` first showed up in
* Note this minimum version in this section of the documentation: https://github.com/AlexsLemonade/scpca-downstream-analyses#2-install-snakemake

**Comment by cbethell** [comment]
Addressed by #278.
