### ISSUE TITLE
Update processed SCE object file name

### ISSUE THREAD

**Issue by cbethell** [AlexsLemonade/scpca-downstream-analyses#298]
**Please provide some background on the proposed additions or changes.**

To begin addressing the [sync ScPCA products epic](https://github.com/AlexsLemonade/scpca-downstream-analyses/issues/291), we will want to ensure that the file name for the processed SCE which would be the output of the core analysis workflow/the input of the module analyses mirrors that which would be downloaded from the ScPCA portal.

**What are the changes that you are proposing?**

We will we want to change the `_processed_sce.rds` file name we currently have in this repo to be `_processed.rds`. In other words, we want to remove `_sce` from any instance where this processed rds file is explicitly named.

**Comment by allyhawkins** [comment]
Closed by #304
