### ISSUE TITLE
Thought: Convert from renv to conda-native R package handling

### ISSUE THREAD

**Issue by jashapiro** [AlexsLemonade/scpca-downstream-analyses#299]
**Please provide some background on the proposed additions or changes.**

The interaction between `conda` and `renv` seems to be a bit brittle, and while `renv` is great for development, for deployments it may be less than ideal, as building packages can be slow, and occasionally fails.

**What are the changes that you are proposing?**

[Bioconda](https://bioconda.github.io/) now has support for just about all of the packages that we use for this workflow, so we could specify all of the packages in the `scpca-renv.yaml` file and remove the post-deploy script that installs packages via renv.

**Please describe the proposed solution.**

Add to `scpca-renv.yaml` all of the packages, with versions, that we use for this workflow. This can be done by searching the [Bioconda package list](https://bioconda.github.io/conda-package_index.html) for the appropriate `r-*` and `bioconductor-*` packages. 

If we keep the `renv` installation in parallel would probably need to rewrite the `snakemake` rules to be sure that they are using `R --vanilla` to ensure that we are using the conda-based R packages and not the ones that `renv` is expecting. 

**What potential "gotchas" do we know of?**

Keeping the versions in sync between the renv  and conda yaml file may be a challenge... I can't think of an easy solution here other than vigilance.

There may also be packages that are not available in bioconda that I have not yet found, but it seems like most of bioconductor is available there, so I expect this is possible.

**Comment by allyhawkins** [comment]
Closed by #322
