### ISSUE TITLE
Update miQC filtering to also remove cells with low gene count

### ISSUE THREAD

**Issue by allyhawkins** [AlexsLemonade/scpca-downstream-analyses#308]
**Please provide some background on the proposed additions or changes.**

The core workflow has two separate filtering modes, manual or miQC. However in `scpca-nf` when we do filtering we use a combination of miQC and removing cells below a minimum gene cutoff. We should do the same here, so if miQC is used, we should also remove cells with a low number of genes detected. We should also use the same default number for minimum number of genes. 

Additionally, we store the information for filtering slightly differently in `scpca-nf` vs. in the core workflow here. We probably want to make the changes to the metadata here so that they match. Even though we don't use them downstream, I think it would be important for things to be in sync. 

**What are the changes that you are proposing?**

In addition to removing cells that do not pass miQC, cells with a total number of genes below the minmum number of genes detected should be removed during the filter step. 

**Please describe the proposed solution.**

In the `01-filter-sce.R` script, if the filtering method chose is `miQC` then we should also filter using the `detected` column in the `colData`. This should be done after using the `miQC::filterCells` function. 

Additionally, the default value for `detected_gene_cutoff` should be changed to 200 to match the value in `scpca-nf`. 

The metadata will also need to be updated, specifically the filtering method should be stored as `scpca_filter_method` and either `Minimum_gene_cutoff` or `miQC`. We also want to chnage `detected_gene_cutoff` to be `min_gene_cutoff` and store it for both filtering methods. 

**What potential "gotchas" do we know of?**

**Additional context or questions**

**Comment by cbethell** [comment]
Addressed by #317
