### ISSUE TITLE
Change metadata for normalization

### ISSUE THREAD

**Issue by allyhawkins** [AlexsLemonade/scpca-downstream-analyses#309]
**Please provide some background on the proposed additions or changes.**

In `scpca-nf` the normalization method is stored as either `deconvolution` or `log-normalization`. We should update how we store normalization in the core workflow to match. 

**What are the changes that you are proposing?**

The normalize script will have to be updated to change how the normalization method is stored in the metadata to match `scpca-nf`.

**Please describe the proposed solution.**

Normalization should either be `deconvolution` or `log-normalization`. Documentation will also need to be updated.

**Comment by cbethell** [comment]
Addressed by #318
