### ISSUE TITLE
Change how variable genes are stored

### ISSUE THREAD

**Issue by allyhawkins** [AlexsLemonade/scpca-downstream-analyses#310]
**Please provide some background on the proposed additions or changes.**

The highly variable genes need to be stored in the same way they are from `scpca-nf`, which is `highly_variable_genes` in the metadata of the SCE object. 

**What are the changes that you are proposing?**

Update the name of the variable for the highly variable genes in the dimensionality reduction script to be `highly_variable_genes`. Documentation will also need to be updated.

**Comment by cbethell** [comment]
Addressed by #318
