### ISSUE TITLE
Test clustering and GOI workflow with processed SCE objects from ScPCA

### ISSUE THREAD

**Issue by allyhawkins** [AlexsLemonade/scpca-downstream-analyses#312]
Before we release the changes to sync up the new updates in `scpca-nf` with the workflows here, we should be sure to grab a few samples from ScPCA and run the processed SCE objects through the two workflows to make sure that we don't see any errors that pop up that we've missed.

**Comment by cbethell** [comment]
I have now successfully tested the clustering and GOI workflows with the following data downloaded from the portal:

- Single-cell sample [SCPCS000123](https://scpca.alexslemonade.org/projects/SCPCP000004#samples)
- Single-nuclei sample [SCPCS000122](https://scpca.alexslemonade.org/projects/SCPCP000004#samples)
- Single-cell sample [SCPCS000294](https://scpca.alexslemonade.org/projects/SCPCP000005#samples)

I got all of the expected output files from running both workflows so I am marking this issue as completed (will re-open if there are any objections)!
