### ISSUE TITLE
Add information to documentation on how to run modules using data from ScPCA

### ISSUE THREAD

**Issue by allyhawkins** [AlexsLemonade/scpca-downstream-analyses#313]
**Please provide some background on the proposed additions or changes.**

Although we say that users can use ScPCA data that they have downloaded and run it right through the portal, I don't think we've done a good job of providing explicit instructions on how they would set up the workflows using data from the portal. For example, if they have downloaded data from the portal they will receive a `libraries-metadata.csv` that actually has the sample and library id that they will need to set up their metadata for these workflows. Also the files will already be organized in a way they need. So we can be a bit more explicit about how to set up the workflows. 

**What are the changes that you are proposing?**

We should provide a quickstart guide or some sort of separate documentation that is clearly linked on how to setup the metadata file/ data for using any of the workflows in this repo since the setup is the same. 

**Please describe the proposed solution.**

We should include clear step by step instructions that are easily linked from the main readme on how to set up the workflows when using scpca data. Also, we might think of providing a specific example using scpca data that is already available, like an example metadata file showing the scpca ids and where they would go in the metadata needed to run this workflow. 

**What potential "gotchas" do we know of?**

**Additional context or questions**

One idea that I did think of is actually adding in a prep step to the workflow where if the data is from ScPCA they can provide the directory holding the scpca data and we can grab the metadata file from that directory and then create the file needed to run the modules. But I think that might be a future idea. We would probably still need a way for users to specify either the entire project or a list of sample/ library ids.

**Comment by cbethell** [comment]
Per https://github.com/AlexsLemonade/scpca-downstream-analyses/pull/324#pullrequestreview-1355011602, we will also want to include a section before `Running the workflow` that states what the expected input files are more explicitly.

**Comment by cbethell** [comment]
Addressed by #326
