### ISSUE TITLE
Restructure running the workflow section in README

### ISSUE THREAD

**Issue by dvenprasad** [AlexsLemonade/scpca-downstream-analyses#319]
**Please provide some background on the proposed additions or changes.**
There two issues but they are related to one another and we should consider both the issues for the solution. 

During evals:
1) when users were ready to run the workflow, they consistently modified the paths in both the config file as well as the command. It is sufficient to only modify it one place, but that is not coming through with how the information is presented. 

2) Modifying the paths on the command line is a pain. Unless someone is a super-user, people are more likely to copy the command and then modify it with the parameters. 
 

**Please describe the proposed solution.**

1) We restructure the documentation so it is `configure config file` -> `run pipeline`. We encourage people to modify the paths (or other parameters) in the config file. 

2) The default running the workflow command omits the path options.

3) We can tuck away command line options in a different file. We can present the options similar to a [man {cmd}](https://man7.org/linux/man-pages/man1/ls.1.html) document.

**Comment by cbethell** [comment]
Addressed by #328
