### ISSUE TITLE
Rename Sections 2 and 3 in README

### ISSUE THREAD

**Issue by dvenprasad** [AlexsLemonade/scpca-downstream-analyses#320]
**Please provide some background on the proposed additions or changes.**

The titles of each of section is a step to take to run the workflow. Sections 2. Input Data Format and 3.Metadata File Format does not indicate what action is expected of users

**Please describe the proposed solution.**
Rename the sections to be action oriented than subject oriented. 

For example, we can rename the sections to:

2. Verify Input Data Format
3. Create Metadata File

**Comment by cbethell** [comment]
Addressed by #328
