### ISSUE TITLE
Add theme and updated labels to GOI plots

### ISSUE THREAD

**Issue by allyhawkins** [AlexsLemonade/scpca-downstream-analyses#325]
In reviewing some of the reports today, I noticed that we have some plots that are using the default theme in `ggplot` still and have no formatting of legends. We should go through and add a consistent theme, preferably `theme_bw()` to all the plots in the GOI module. We should also adjust the legends and axis labels to be a bit more aesthetically pleasing.

**Comment by jashapiro** [comment]
We should probably do this with a `ggplot::theme_set()` call in an early setup chunk to reduce redundancy.

**Comment by cbethell** [comment]
Addressed by #330
