### ISSUE TITLE
Add integration order to integration script

### ISSUE THREAD

**Issue by allyhawkins** [AlexsLemonade/scpca-downstream-analyses#347]
**Please provide some background on the proposed additions or changes.**

When providing a merged object to the integration script in #346, no integration order is specified. This will not matter for `harmony`, but it will matter for `fastMNN` as the default is to merge in the input order. We did some testing in `sc-data-integration` regarding integration order, and found that the `auto.merge` option in `fastMNN` worked well and we would like to be able to implement that when we implement integration. 

**What are the changes that you are proposing?**

We will want to be able to use the `auto.merge` option for `fastMNN` integration, but also allow for a user to decide they would like to use the input order for integration. This means adding a new argument to account for integration order specifically for `fastMNN` to the script being added in #346. 
We also need to add the `merge.order` option which will allow for users to specify the merge order if different from the input integration order. 

**Please describe the proposed solution.**

We need to add an option for using `auto.merge` to the script like the one found in `sc-data-integration`: 
https://github.com/AlexsLemonade/sc-data-integration/blob/3994b1934e255a129d5efcb56fa5fa2130d075dc/scripts/03a-integrate-sce.R#L142-L147

This argument should be added to the script in #346 and then implemented with `auto.merge = opt$fastmnn_auto_merge`. 
We will also need to account for this argument in the snakefile and set the default to use `auto.merge`, with the option of turning it off. 

Alternatively, if users want to use a specified order for their libraries, we should create an additional argument for `merge.order`. This should only be used if `auto.merge` is set to false and will have a vector of library id's in the order of which they should be merged. 

**What potential "gotchas" do we know of?**

My one concern with allowing for the merge order as input is if we have multiple groups that are being integrated, the merge order will need to be specified for each group. This will only be the case if that option is being used, but we should think about how we would want to implement that (maybe a separate column for the order in the metadata?).

**Comment by cbethell** [comment]
Addressed by #348
