### ISSUE TITLE
Update packages to fix error when building conda environment

### ISSUE THREAD

**Issue by allyhawkins** [AlexsLemonade/scpca-downstream-analyses#374]
In testing that the workflow was good to go for release, Chante noticed an error when building the conda environment. Specifically, the version we were using of `GenomeInfoDbData` is outdated and the package download is failing. One solution is to update the version that we use to the most [recent version of `GenomeInfoDBData`](https://bioconda.github.io/recipes/bioconductor-genomeinfodbdata/README.html), but that relies on R 4.3 so we would also need to update base R (and other packages presumably). 

My messages with Chante are gone sadly, but Stephanie was looking into this and also found the same error. I'm including that here for reference. 
![image](https://github.com/AlexsLemonade/scpca-downstream-analyses/assets/54039191/189a5e45-c356-450b-a5b6-4412df8720c2)

**Comment by jashapiro** [comment]
It looks like the latest R4.2 version is `1.34.9`.  Can we try that one? Other packages might need to be updated to follow that, but the version of R should be the same. Other versions are at: https://quay.io/repository/biocontainers/bioconductor-genomeinfodb?tab=tags.

**Comment by allyhawkins** [comment]
> Oh, my bad, I was looking at the wrong package. I am not having trouble installing genomeinfodbdata 1.2.9, so I'm not sure exactly what the issue is. What command was used to create the environment there? If setup_envs.sh is not used, it may be using the wrong architecture.

She was running `bash setup_envs.sh` and hit the error. I am running it now to see if I run into the same thing.

**Comment by jashapiro** [comment]
> So when I run it on the server it works and I think it's because it's probably using my cache to build the environment. But the workflow fails with an error of trying to use CRAN without setting a mirror

A couple questions here: when you say the workflow fails, which one do you mean? If it is one of the "real" workflows, I would not expect those to be calling out to CRAN, so something may be missing from the environment. If you have a full log file to post, that would potentially be more helpful.

**Comment by allyhawkins** [comment]
I had run `snakemake -s integration.snakefile -c4` and got the error I sent above. That was the entirety of the log file from that job. Here's the log file for the run. 
[integration-workflow.log](https://github.com/AlexsLemonade/scpca-downstream-analyses/files/12339504/integration-workflow.log)

**Comment by allyhawkins** [comment]
Closed by #377
