### ISSUE TITLE
Update snakemake version docs

### ISSUE THREAD

**Issue by sjspielman** [AlexsLemonade/scpca-downstream-analyses#375]
Today I realized that neither `conda` nor `snakemake` were installed in my server account, so I got myself some fresh installs. Then I went to build the environment for this repo to work on some things, but got a surprising error:

<img width="808" alt="Screenshot 2023-08-14 at 1 02 11 PM" src="https://github.com/AlexsLemonade/scpca-downstream-analyses/assets/4701111/0a5e60c9-cbee-4edf-9fb6-a69e062d480a">

From my fresh install, I ended up with `python 3.11` and `snakemake 7.32.3`, both of which satisfy our current docs requirements, but clearly something is up! So..

- First, I downgraded python to `3.9`. The error persisted
- Then, I downgraded `snakemake` to `7.24.2`, which is compatible with our docs (>7.20.0), and also that's the version @allyhawkins has so it seemed like a good place for success. Indeed **the error went away** and I built the environment successfully.

So, seems something happened _probably_ in the `7.3` release of snakemake (I don't know that for sure, but based on semantic versioning, probably?). 
The quickest fix here is simply to update our docs that snakemake needs to be `\in [7.20.0, 7.3)`, but more generally we might want to think about workflow compatibility (as a separate much larger issue, which depends also on the future direction of this project!).

**Comment by jashapiro** [comment]
`7.3` is well before `7.24`... semantic versions are not zero padded. So we are looking for something that changed between `7.24` and `7.32` 

That said, I think we want to figure out what the correct way to handle what we had as `workflow.use_conda`, as that doesn't seem to be the right place to look anymore.

**Comment by sjspielman** [comment]
Possibly worth noting that @allyhawkins and I can only build the environment on the server, but not at all locally. Probably issue forthcoming about that...

**Comment by jashapiro** [comment]
The crux of this particular issue seems to be the attempt to set `workflow.use_conda`. It mostly appears that `snakemake` does not want you to change this particular property (and enforces it now, when it might not have before), and while we could force it by setting `workflow._use_conda` I really don't want to do that. 

I'm not sure if there is a better way to change things, but I think we should try to stay away from modifying the the `workflow` object, as that seems likely to be brittle.

**Comment by allyhawkins** [comment]
Closed by #376
